---
title: "Lab 3: 12 Days of Christmas"
author: "Alexandra Grover" 
date: October 14,2024
embed-resources: true
execute:
    echo: false
    eval: false
    ouput: false
---

In [2]:
#Lab 3
import numpy as np 
import pandas as pd

In [3]:
xmas= pd.read_csv("/Users/alexandra/Desktop/GSB-544/Labs/Lab3/xmas.csv")
xmas

    Day Day.in.Words  Gift.Item        Verb Adjective        Location
0     1        first  partridge         NaN       NaN  in a pear tree
1     2       second       dove         NaN    turtle             NaN
2     3        third        hen         NaN    french             NaN
3     4       fourth       bird         NaN   calling             NaN
4     5        fifth       ring         NaN    golden             NaN
5     6        sixth      goose    a-laying       NaN             NaN
6     7      seventh       swan  a-swimming       NaN             NaN
7     8       eighth       maid   a-milking       NaN             NaN
8     9        ninth       lady     dancing       NaN             NaN
9    10        tenth       lord   a-leaping       NaN             NaN
10   11     eleventh      piper      piping       NaN             NaN
11   12      twelfth    drummer    drumming       NaN             NaN

In [4]:
def pluralize_gift(gift):
  """
  Returns plural of a noun
  
  Parameters
  ----------
  gift: str
    A noun
    
  Return
  ------
  str
    Plural version
  """

  if "oo" in gift:
    gift = gift.replace("oo", "ee")
  elif gift[-1]=="y":
    gift = gift.replace("y", "ies")
  else:
    gift = gift +"s"

  return gift

In [5]:
#test: Should work
pluralize_gift("goose")

# Will work if your function is vectorized! 
(xmas['Gift.Item'].apply(pluralize_gift))

0     partridges
1          doves
2           hens
3          birds
4          rings
5          geese
6          swans
7          maids
8         ladies
9          lords
10        pipers
11      drummers
Name: Gift.Item, dtype: object

**Function 2: make_phrase()**

In [6]:
def make_phrase(num, num_word, item, verb, adjective, location):
  """
   Constructs a phrase given parameters.
    
    Parameters
    ----------
    num : int
        The numeric value for the gift.
    num_word : str
        The number in word form (e.g., 'ten', 'five').
    item : str
        The gift item.
    verb : str or pd.Series
        The verb associated with the gift (can have NaNs).
    adjective : str or pd.Series
        The adjective describing the gift (can have NaNs).
    location : str or pd.Series
        The location where the gift is found (can have NaNs).
    
    Returns
    -------
    str
        A descriptive phrase for the gift.
        *Chat gpt helped with writing this 
  """
  
    ## Step 1: Replace NAs with blank strings
  if pd.isnull(verb):
    verb= ""

  if pd.isnull(adjective):
    adjective= ""

  if pd.isnull(location):
    location= ""
    
    ## Step 2: If the day number is larger than 1, the gift items need pluralized!
    ### Hint: call the function you created above!

  if num> 1:
    item=pluralize_gift(item)
    
    ## Step 3: Figure out if a gift item starts with a vowel

  vowels = "AEIOUaeiou"
  isVowel = item[0] in vowels

    ## Step 4: For the first day, if the gift item starts with a vowel, replace the day with "an" and if the gift item does not start with a vowel, replace the day with "a" (e.g. a partridge in a pear tree). If it is not the first day, use just the number word (e.g. ten lords a leap)
    
  if num == 1:
    if isVowel == True: 
      num_word = "an"
    else:
      num_word = "a"
    
  ## Step 5: Put all of the pieces together into one string and return!

  text = num_word + " "+ adjective + " "+ item+" " + verb + location
  return text.replace("  ", " ").strip()

In [7]:
#test: make_phrase(num = "10",
            #num_word = "ten",
            #item = " " ,
            #verb = "a-leaping", 
            #adjective = "lords", 
            #location = " ")

In [8]:
number_to_word= {
    "first": 'one',
    "second": 'two',
    "third": 'three',
    "fourth": 'four',
    "fifth": 'five',
    "sixth": 'six',
    "seventh": 'seven',
    "eighth": 'eight',
    "ninth": 'nine',
    'tenth': 'ten',
    "eleventh": 'eleven',
    "twelfth": 'twelve'
}
xmas['Day.Words']= xmas["Day.in.Words"].map(number_to_word)

In [9]:
#test
num_words = "one"
item = "partridge"
verb =""
adjective=""
location="in a pear tree"
num_words + " "+ adjective + " "+ item+" " + verb + location
text = num_words + " "+ adjective + " "+ item+" " + verb + location
text.replace("  ", " ").strip()

'one partridge in a pear tree'

In [10]:
xmas

    Day Day.in.Words  Gift.Item        Verb Adjective        Location Day.Words
0     1        first  partridge         NaN       NaN  in a pear tree       one
1     2       second       dove         NaN    turtle             NaN       two
2     3        third        hen         NaN    french             NaN     three
3     4       fourth       bird         NaN   calling             NaN      four
4     5        fifth       ring         NaN    golden             NaN      five
5     6        sixth      goose    a-laying       NaN             NaN       six
6     7      seventh       swan  a-swimming       NaN             NaN     seven
7     8       eighth       maid   a-milking       NaN             NaN     eight
8     9        ninth       lady     dancing       NaN             NaN      nine
9    10        tenth       lord   a-leaping       NaN             NaN       ten
10   11     eleventh      piper      piping       NaN             NaN    eleven
11   12      twelfth    drummer    drumming       NaN             NaN    twelve

In [11]:
#full_phrase()
xmas['full_phrase']= xmas.apply(lambda x: make_phrase(x['Day'],
                                          x['Day.Words'],
                                          x['Gift.Item'],
                                          x['Verb'],
                                          x['Adjective'],
                                          x['Location']),
                                           axis=1)

In [12]:
xmas['full_phrase']

0     a partridge in a pear tree
1               two turtle doves
2              three french hens
3             four calling birds
4              five golden rings
5             six geese a-laying
6         seven swans a-swimming
7          eight maids a-milking
8            nine ladies dancing
9            ten lords a-leaping
10          eleven pipers piping
11      twelve drummers drumming
Name: full_phrase, dtype: object

In [13]:
#test
#make_phrase(num, num_word, item, verb, adjective, location):
make_phrase(xmas.iloc[0]["Day"],
            xmas.iloc[0]["Day.Words"],
            xmas.iloc[0]["Gift.Item"],
            xmas.iloc[0]["Verb"],
            xmas.iloc[0]["Adjective"],
            xmas.iloc[0]["Location"],
)

'a partridge in a pear tree'

In [14]:
xmas

    Day Day.in.Words  ... Day.Words                 full_phrase
0     1        first  ...       one  a partridge in a pear tree
1     2       second  ...       two            two turtle doves
2     3        third  ...     three           three french hens
3     4       fourth  ...      four          four calling birds
4     5        fifth  ...      five           five golden rings
5     6        sixth  ...       six          six geese a-laying
6     7      seventh  ...     seven      seven swans a-swimming
7     8       eighth  ...     eight       eight maids a-milking
8     9        ninth  ...      nine         nine ladies dancing
9    10        tenth  ...       ten         ten lords a-leaping
10   11     eleventh  ...    eleven        eleven pipers piping
11   12      twelfth  ...    twelve    twelve drummers drumming

[12 rows x 8 columns]

In [15]:
#test
pd.isnull(verb)

False

**Function 3: sing_day()**

In [16]:
# Step 1: Setup the intro line
get_word = {
    1: 'first',
    2: 'second',
    3: 'third',
    4: 'fourth',
    5: 'fifth',
    6: 'sixth',
    7: 'seventh',
    8: 'eighth',
    9: 'ninth',
    10: 'tenth',
    11: 'eleventh',
    12: 'twelveth'}
  
    # convert "1" to "first" etc.
    #intro = "On the " + num_word + " day of Christmas, my true love sent to me:"
   #Test 10 
get_word.get(10)

'tenth'

In [17]:
#intro = "On the " + num_word + " day of Christmas, my true love sent to me:"

In [18]:

def sing_day(dataset, num, phrase_col):
  """
    Generates the "12 Days of Christmas" lyrics for a specified day.

    Parameters
    ----------
    dataset : pandas.DataFrame
        DataFrame with gift phrases for each day.
    num : int
        The day number for the lyrics (ex: 1 for the first day).
    phrase_col : str
        Column name containing the gift phrases.
    Returns
    -------
    str
        The song lyrics for the specified day, starting with an intro line 
        and then lists the gifts in reverse order. Includes "and" before "a partridge 
        in a pear tree" from the second day onward.
        *Chat GPT helped write this
    ``` 
  """
  # Step 1: Setup the intro line
  num_word = get_word.get(num)  # convert "1" to "first" etc.
  intro = "On the " + num_word + " day of Christmas, my true love sent to me:"
  
  
  # Step 2: Sing the gift phrases
  # Hint: What order are they gifts sung in each day?
  gifts = ""
  nums = np.arange(num,0,-1)
  for i in nums:
    if i == 2:
      gifts = gifts + " " + dataset.iloc[i-1][phrase_col]+ " " + "and" + "," +"\n"
    else:
      gifts = gifts + " " + dataset.iloc[i-1][phrase_col]+ "," +"\n"

  # Step 3: Put it all together and return

  final = intro +"\n" + gifts 
  return(final[:-2])

In [19]:
#test 3rd day
xmas.iloc[2]['full_phrase']

'three french hens'

In [20]:
#test twelfth day
print(sing_day(xmas, 12, "full_phrase"))

On the twelveth day of Christmas, my true love sent to me:
 twelve drummers drumming,
 eleven pipers piping,
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree
On the twelveth day of Christmas, my true love sent to me:
 twelve drummers drumming,
 eleven pipers piping,
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

In [21]:
#test
nums=3
nums = np.arange(nums,0,-1)
for i in [nums]:
    print(i)

[3 2 1]
[3 2 1]

In [22]:
#All days 
song = map(lambda i: sing_day(xmas, i, "full_phrase"), range(1,13) )
print("\n\n". join (list (song) ) )

On the first day of Christmas, my true love sent to me:
 a partridge in a pear tree

On the second day of Christmas, my true love sent to me:
 two turtle doves and,
 a partridge in a pear tree

On the third day of Christmas, my true love sent to me:
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the fourth day of Christmas, my true love sent to me:
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the fifth day of Christmas, my true love sent to me:
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the sixth day of Christmas, my true love sent to me:
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the seventh day of Christmas, my true love sent to me:
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the eighth day of Christmas, my true love sent to me:
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the ninth day of Christmas, my true love sent to me:
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the tenth day of Christmas, my true love sent to me:
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the eleventh day of Christmas, my true love sent to me:
 eleven pipers piping,
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the twelveth day of Christmas, my true love sent to me:
 twelve drummers drumming,
 eleven pipers piping,
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree
On the first day of Christmas, my true love sent to me:
 a partridge in a pear tree

On the second day of Christmas, my true love sent to me:
 two turtle doves and,
 a partridge in a pear tree

On the third day of Christmas, my true love sent to me:
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the fourth day of Christmas, my true love sent to me:
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the fifth day of Christmas, my true love sent to me:
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the sixth day of Christmas, my true love sent to me:
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the seventh day of Christmas, my true love sent to me:
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the eighth day of Christmas, my true love sent to me:
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the ninth day of Christmas, my true love sent to me:
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the tenth day of Christmas, my true love sent to me:
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the eleventh day of Christmas, my true love sent to me:
 eleven pipers piping,
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

On the twelveth day of Christmas, my true love sent to me:
 twelve drummers drumming,
 eleven pipers piping,
 ten lords a-leaping,
 nine ladies dancing,
 eight maids a-milking,
 seven swans a-swimming,
 six geese a-laying,
 five golden rings,
 four calling birds,
 three french hens,
 two turtle doves and,
 a partridge in a pear tree

In [23]:
#Bonus last part 
xmas2 = pd.read_csv("/Users/alexandra/Desktop/GSB-544/Labs/Lab3/xmas_2.csv")

In [24]:
number_to_word= {
    "first": 'one',
    "second": 'two',
    "third": 'three',
    "fourth": 'four',
    "fifth": 'five',
    "sixth": 'six',
    "seventh": 'seven',
    "eighth": 'eight',
    "ninth": 'nine',
    'tenth': 'ten',
    "eleventh": 'eleven',
    "twelfth": 'twelve'
}
xmas2['Day.Words']= xmas2["Day.in.Words"].map(number_to_word)

In [25]:
#full_phrase 2
xmas2['full_phrase']= xmas2. apply(lambda x: make_phrase(x["Day"],
                                            x['Day.Words'],
                                            x['Gift.Item'],
                                            x['Verb'],
                                            x['Adjective'],
                                            x['Location']), axis=1)

In [26]:
#Test 
xmas2['full_phrase']= xmas2.apply(lambda x: make_phrase(x['Day'],
                                          x['Day.Words'],
                                          x['Gift.Item'],
                                          x['Verb'],
                                          x['Adjective'],
                                          x['Location']), axis=1)
print(sing_day(xmas2, 12, "full_phrase"))

On the twelveth day of Christmas, my true love sent to me:
 twelve hours sleeping,
 eleven friends goodbye-ing,
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly
On the twelveth day of Christmas, my true love sent to me:
 twelve hours sleeping,
 eleven friends goodbye-ing,
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

In [28]:
song = map(lambda i: sing_day(xmas2, i, "full_phrase"), range(1,13) )
print("\n\n". join (list (song) ))

On the first day of Christmas, my true love sent to me:
 an email from Cal Poly

On the second day of Christmas, my true love sent to me:
 two meal points and,
 an email from Cal Poly

On the third day of Christmas, my true love sent to me:
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the fourth day of Christmas, my true love sent to me:
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the fifth day of Christmas, my true love sent to me:
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the sixth day of Christmas, my true love sent to me:
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the seventh day of Christmas, my true love sent to me:
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the eighth day of Christmas, my true love sent to me:
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the ninth day of Christmas, my true love sent to me:
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the tenth day of Christmas, my true love sent to me:
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the eleventh day of Christmas, my true love sent to me:
 eleven friends goodbye-ing,
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the twelveth day of Christmas, my true love sent to me:
 twelve hours sleeping,
 eleven friends goodbye-ing,
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly
On the first day of Christmas, my true love sent to me:
 an email from Cal Poly

On the second day of Christmas, my true love sent to me:
 two meal points and,
 an email from Cal Poly

On the third day of Christmas, my true love sent to me:
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the fourth day of Christmas, my true love sent to me:
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the fifth day of Christmas, my true love sent to me:
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the sixth day of Christmas, my true love sent to me:
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the seventh day of Christmas, my true love sent to me:
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the eighth day of Christmas, my true love sent to me:
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the ninth day of Christmas, my true love sent to me:
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the tenth day of Christmas, my true love sent to me:
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the eleventh day of Christmas, my true love sent to me:
 eleven friends goodbye-ing,
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly

On the twelveth day of Christmas, my true love sent to me:
 twelve hours sleeping,
 eleven friends goodbye-ing,
 ten loads of laundry,
 nine parties bumping,
 eight moms a-calling,
 seven seniors stressing,
 six graders grading,
 five practice exams,
 four course reviews,
 three lost pens,
 two meal points and,
 an email from Cal Poly